# 1.4 Softmax

## 1.4.1 Naive Softmax

$$ X = [x_1,x_2,...x_n]$$

$$ softmax(\hat{x_i}) = \frac{e^{x_i}}{\Sigma_{j=1}^n e^{x_j}} $$

In [2]:
import torch

X = torch.Tensor([-0.1, 0.2, 0.45, -0.27, 0.58])

def naive_softmax(x: torch.Tensor) -> torch.Tensor:
    exp_x = torch.exp(x)
    return exp_x / exp_x.sum()

print(naive_softmax(X))

tensor([0.1449, 0.1956, 0.2512, 0.1223, 0.2860])




## 1.4.2 Safe Softmax

Because the power computation will lead to overflow, we can make the dividant and divisor smaller by minusing the maximum $x_i$.

$$ x_k = max(x_1, x_2,...,x_n)$$
$$ softmax(\hat{x_i}) = \frac{e^{x_i-x_k}}{\Sigma_{j=1}^n e^{x_j-x_k}} $$

Then every power number will be less than 0.

In [ ]:
def safe_softmax(x: torch.Tensor) -> torch.Tensor:
    x = x - torch.max(x)
    exp_x = torch.exp(x)
    return exp_x / exp_x.sum()


print(safe_softmax(X))

tensor([0.1449, 0.1956, 0.2512, 0.1223, 0.2860])


## 1.4.3 Online Softmax

The maximum calculation will need one $O(n)$ loop. We want to do it in the sum loop.

In [6]:
def online_softmax(x: torch.Tensor) -> torch.Tensor:
    exp_sum = 0
    max_x = x[0]
    for x_i in x:
        new_max = max(max_x, x_i)
        exp_sum = exp_sum * torch.exp(max_x-new_max) + torch.exp(x_i-new_max)
        max_x = new_max
    return torch.exp(x-max_x) / exp_sum

print(online_softmax(X))

tensor([0.1449, 0.1956, 0.2512, 0.1223, 0.2860])


## references
